baseURL: "https://omarolivarez.github.io/" 
title: Omar Olivarez
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Teaching
          url: /courses/
          weight: 2
        - name: CV
          url: /cv.pdf
          weight: 3        
        # - name: HBS Profile
        #   url: https://www.hbs.edu/faculty/Pages/profile.aspx?facId=1308412
        #   weight: 4
        - name: Miscellany
          url: /misc/
          weight: 4

params:
    description: "This website hosts Omar Olivarez's research and career information."
    author: Omar Olivarez
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Omar Olivarez
          subtitle: "Welcome! I am a PhD candidate in the Technology & Operations Management unit at Harvard Business School. 
          My interests lie at the intersection of automation, labor, and management. 
          I am interested in using econometric and experimental methods to study how firms can introduce automation in the workplace.<br><br>
          Prior to matriculating at Harvard, I worked in the Tech industry. 
          I spent some time as a software developer at Southwest Airlines and as a product operations manager at Google. 
          I received my undergrad in Management Information Systems from the University of Texas."
          imageUrl: "/picture.jpg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Omar Olivarez
          buttons:
            - name: Papers
              url: /papers/
            - name: Teaching
              url: /courses/
            - name: CV
              url: /cv.pdf
            # - name: HBS Profile
            #   url: https://www.hbs.edu/faculty/Pages/profile.aspx?facId=1308412
            - name: Miscellany
              url: /misc/
            # - name: Design
            #   url: /design/
            # - name: Book
            #   url: /b1/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: /tags/
            # - name: Archive
            #   url: /archive/

    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:oolivarez@hbs.edu

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Omar Olivarez"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
